name: Bug report
description: Report a problem in NovaCMS
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, reproducible example.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: e.g., 1.0.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste relevant logs (redact secrets).
      render: shell
